version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - Spring.profiles.active=deploy
    ports:
      - "8189:8189"
    networks:
      - app-network
      - proxy
    deploy:
      resources:
        limits:
          memory: 512m

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m

  proxy:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    networks:
      - proxy

  grafana:
    build: './configuration/grafana'
    ports:
      - "3000:3000"
    user: root
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    user: root
    volumes:
      - ./configuration/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus:/prometheus
    networks:
      - app-network

networks:
  proxy:
    driver: bridge
  app-network:
    driver: bridge

