spring:
  application:
    name: "axioma"
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    user: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    hikari:
     connection-timeout: 33000
     username: postgres
     password: postgres
     jdbc-url: jdbc::/postgresql://db:5432/postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8189}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application : ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]" : true

jwt:
  secret: axioma-app
  expiration: 604800
  header: Authorization

