spring:
  flyway:
    enabled: true
    baseline-on-migrate: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://bhhtkchkxfdlhb:a70c2288c717c91deb4bb6660f582154ad01b5c99fda40122a58d14507b17475@ec2-34-248-169-69.eu-west-1.compute.amazonaws.com:5432/d7ei1mfe0hpf04
    username: bhhtkchkxfdlhb
    password: a70c2288c717c91deb4bb6660f582154ad01b5c99fda40122a58d14507b17475
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8189}

jwt:
  secret: axioma-app
  expiration: 604800
  header: Authorization

