name: axioma ci/cd

on:
  push:
    branches: 
      - v1

jobs:
  test:

    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    services:
      postgres:
        image:
          postgres:latest
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: $ {{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: mvn clean verify
        run: mvn -B clean verify -DskipTests
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: unnecessary

      - name: add host to known_hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: rsync transfer
        run: |
          rsync -avz -e "ssh -v -p ${{ secrets.SSH_PORT }}" target/*.jar ${{ secrets.SERVER_HOST }}:/axioma-project/
          rsync -avz -e "ssh -v -p ${{ secrets.SSH_PORT }}" ./configuration/ ${{ secrets.SERVER_HOST }}:/axioma-project/configuration/
          
      - name: SSH configuration
        run: |
          mkdir -p ~/.ssh/
          echo ${{ secrets.KEY }} > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ secrets.SERVER_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: run docker compose
        run: ssh staging 'cd ../axioma-project && pwd && ls -l -a -h && docker-compose up --detach --build --force-recreate'
