name: axioma ci/cd

on:
  push:
    branches: 
      - v1

jobs:
  test:

    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    services:
      postgres:
        image:
          postgres:latest
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: $ {{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup tools
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Maven package and verify
        run: mvn -B clean verify -DskipTests

      - name: Check current directory
        run: pwd

      - name: Check files in directory
        run: ls -l
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SERVER_HOST_NAME }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz -e "ssh -v -p ${{ secrets.SSH_PORT }}" target/*.jar ${{ secrets.SERVER_HOST_NAME }}:/axioma-project/
          rsync -avz -e "ssh -v -p ${{ secrets.SSH_PORT }}" ./configuration/ ${{ secrets.SERVER_HOST_NAME }}:/axioma-project/configuration/
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ secrets.SERVER_HOST_NAME }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Run docker-compose file to up an application and environment
        run: ssh staging 'cd ../axioma-project && pwd && ls -l -a -h && docker-compose up --detach --build --force-recreate'
