name: test

on:
  push:
    branches: 
      - v1

jobs:
  test:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    steps:
    
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name : echo all
        run: echo ${{ secrets.KEY }}
